# Binds ArangoDB PVC data to a path on the Minikube node's *native* filesystem (inside the VM).
# RocksDB requires directory fsync, which 9p does not support, so cannot mount data to host
apiVersion: storage.arangodb.com/v1alpha
kind: ArangoLocalStorage
metadata:
  name: arango-minikube-local-data
spec:
  storageClass:
    name: arango-minikube-data
  localPath:
    - /var/lib/arango-local-data
